version: "3"

services:
  namenode:
    image: hdfs/namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
  datanode1:
    image: hdfs/datanode
    volumes:
      - datanode:/hadoop/dfs/data1
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
  datanode2:
    image: hdfs/datanode
    volumes:
      - datanode:/hadoop/dfs/data2
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9865:9865"
  hive-server:
    image: hive
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: hive
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 mysql:3306"
    ports:
      - "9083:9083"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  presto-coordinator:
    image: presto
    ports:
      - "8080:8080"
volumes:
  namenode:
  datanode:
